swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{user_id}/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve a list of the accounts of the user
      description: API for fetching all accounts (checking, savings, credit card) for a specific user
      parameters:
        - in: path
          name: user_id
          description: ID of the user whose accounts to retrieve
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User accounts retrieved successully
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{user_id}/accounts/{account_type}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve a list of the accounts of the user for the current month
      description: API for fetching all accounts (checking, savings, credit card) for a specific user for the current month
      parameters:
        - in: path
          name: user_id
          description: ID of the user
          required: true
          type: string
        - in: path
          name: account_type
          description: Type of account (checking, savings, credit card)
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User accounts retrieved successully
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add a new transaction to a specific account
      description: API for creating another transaction
      parameters:
        - in: path
          name: user_id
          description: ID of the user
          required: true
          type: string
        - in: path
          name: account_type
          description: Type of account (checking, savings, credit card)
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Transaction details
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User create an new transaction successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{user_id}/accounts/{account_type}/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve a list of the accounts of the user for the current month
      description: API for fetching a specific transaction for a user account
      parameters:
        - in: path
          name: user_id
          description: ID of the user
          required: true
          type: string
        - in: path
          name: account_type
          description: Type of the account (checking, savings, credit card)
          required: true
          type: string
        - in: path
          name: transaction_id
          description: ID of the transaction
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: path
          name: user_id
          description: ID of the user
          required: true
          type: string
        - in: path
          name: account_type
          description: Type of the account (checking, savings, credit card)
          required: true
          type: string
        - in: path
          name: transaction_id
          description: ID of the transaction
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: transaction
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete a specific transaction for a user account
      description: API for deleting a specific transaction for a user account
      parameters:
        - in: path
          name: user_id
          description: ID of the user
          required: true
          type: string
        - in: path
          name: account_type
          description: Type of the account (checking, savings, credit card)
          required: true
          type: string
        - in: path
          name: transaction_id
          description: ID of the transaction
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: The id of the transaction
      accountId:
        type: string
        description: The id of the account associated with the transaction
      amount:
        type: number
        description: The amount of the transaction
      description:
        type: string
        description: A short description of the transaction
      date:
        type: string
        format: date-time
        description: The date and time of the transaction
